"""Auto-generated concept aliases from IPhO syllabus.
   DO NOT EDIT BY HAND — regenerate via scripts/build_concept_aliases.py
"""
from __future__ import annotations

CONCEPT_ALIASES_AUTO: dict[str, tuple[str, str, str]] = {
    "ac circuits": ("Electromagnetic fields", "Circuits", "AC circuits: complex amplitude"),
    "ac circuits complex amplitude": ("Electromagnetic fields", "Circuits", "AC circuits: complex amplitude"),
    "accelerations without coriolis term": ("Mechanics", "Kinematics", "Addition of accelerations without the Coriolis term"),
    "active power": ("Electromagnetic fields", "Circuits", "Active power"),
    "addition accelerations without coriolis term": ("Mechanics", "Kinematics", "Addition of accelerations without the Coriolis term"),
    "addition parallel velocities": ("Relativity", "Relativity", "Addition of parallel velocities"),
    "addition velocities angular velocities": ("Mechanics", "Kinematics", "Addition of velocities and angular velocities"),
    "alpha beta gamma decays": ("Quantum Physics", "Structure of matter", "Alpha-, beta- and gamma-decays"),
    "ammeters": ("Electromagnetic fields", "Circuits", "Ammeters"),
    "amp re s force": ("Electromagnetic fields", "Basic concepts", "Ampère's force"),
    "amp re s law": ("Electromagnetic fields", "Integral forms of Maxwell's equations", "Ampère's law (with Maxwell correction)"),
    "amp re s law maxwell correction": ("Electromagnetic fields", "Integral forms of Maxwell's equations", "Ampère's law (with Maxwell correction)"),
    "angular frequency": ("Oscillations and waves", "Single oscillator", "Angular frequency"),
    "angular momentum": ("Mechanics", "Dynamics", "Angular momentum"),
    "approximation geometrical optics": ("Oscillations and waves", "Geometrical optics and photometry", "Approximation of geometrical optics: rays and optical images"),
    "approximation geometrical optics rays optical images": ("Oscillations and waves", "Geometrical optics and photometry", "Approximation of geometrical optics: rays and optical images"),
    "atomic nuclei": ("Quantum Physics", "Structure of matter", "Atomic nuclei"),
    "b field axis circular current loop": ("Electromagnetic fields", "Basic concepts", "B-field on the axis of a circular current loop"),
    "b field simple symmetric systems like straight wire circular loop long solenoid": ("Electromagnetic fields", "Basic concepts", "B-field for simple symmetric systems like straight wire, circular loop and long solenoid"),
    "beats": ("Oscillations and waves", "Interference and diffraction", "Beats"),
    "behaviour near unstable equilibria": ("Oscillations and waves", "Single oscillator", "Behaviour near unstable equilibria"),
    "bernoulli equation": ("Mechanics", "Hydrodynamics", "Bernoulli equation"),
    "biot savart law": ("Electromagnetic fields", "Basic concepts", "Biot-Savart law"),
    "boiling": ("Thermodynamics and statistical physics", "Heat transfer and phase transitions", "Boiling"),
    "boltzmann factor": ("Thermodynamics and statistical physics", "Classical thermodynamics", "Boltzmann factor"),
    "boundary conditions electric field electrostatic potential surface conductors infinity": ("Electromagnetic fields", "Integral forms of Maxwell's equations", "Boundary conditions for the electric field (or electrostatic potential) at the surface of conductors and at infinity"),
    "boundary conditions electric field surface conductors infinity": ("Electromagnetic fields", "Integral forms of Maxwell's equations", "Boundary conditions for the electric field (or electrostatic potential) at the surface of conductors and at infinity"),
    "bragg reflection": ("Oscillations and waves", "Interference and diffraction", "Bragg reflection"),
    "brewster angle": ("Oscillations and waves", "Interaction of electromagnetic waves with matter", "Brewster angle"),
    "buoyancy": ("Mechanics", "Hydrodynamics", "Buoyancy"),
    "calculation fields when integrand almost piece wise constant": ("Electromagnetic fields", "Integral forms of Maxwell's equations", "Using these laws for the calculation of fields when the integrand is almost piece-wise constant"),
    "capacitors capacitance": ("Electromagnetic fields", "Circuits", "Capacitors and capacitance (also for a single electrode with respect to infinity)"),
    "capacitors capacitance single electrode respect infinity": ("Electromagnetic fields", "Circuits", "Capacitors and capacitance (also for a single electrode with respect to infinity)"),
    "capillary pressure": ("Mechanics", "Hydrodynamics", "Capillary pressure"),
    "center mass system summation integration": ("Mechanics", "Statics", "Finding the centre of mass of a system via summation or via integration"),
    "centre mass system summation integration": ("Mechanics", "Statics", "Finding the centre of mass of a system via summation or via integration"),
    "centrifugal force": ("Mechanics", "Dynamics", "Centrifugal force"),
    "centripetal tangential acceleration": ("Mechanics", "Kinematics", "Centripetal and tangential acceleration"),
    "charge conservation": ("Electromagnetic fields", "Basic concepts", "Charge conservation"),
    "charge current": ("Electromagnetic fields", "Basic concepts", "Concepts of charge and current"),
    "charges magnetic field": ("Electromagnetic fields", "Interaction of matter with electric and magnetic fields", "Charges in magnetic field: helicoidal motion"),
    "charges magnetic field helicoidal motion": ("Electromagnetic fields", "Interaction of matter with electric and magnetic fields", "Charges in magnetic field: helicoidal motion"),
    "classical doppler effect": ("Oscillations and waves", "Waves", "The classical Doppler effect"),
    "compton scattering": ("Quantum Physics", "Structure of matter", "Compton scattering"),
    "concept grounded conductors": ("Electromagnetic fields", "Integral forms of Maxwell's equations", "Concept of grounded conductors"),
    "concept heat conductivity": ("Thermodynamics and statistical physics", "Heat transfer and phase transitions", "Concept of heat conductivity"),
    "concepts charge current": ("Electromagnetic fields", "Basic concepts", "Concepts of charge and current"),
    "concepts thermal equilibrium reversible processes": ("Thermodynamics and statistical physics", "Classical thermodynamics", "Concepts of thermal equilibrium and reversible processes"),
    "conservation energy momentum elastic non elastic interaction particles": ("Relativity", "Relativity", "Conservation of energy and momentum for elastic and non-elastic interaction of particles"),
    "constant current sources": ("Electromagnetic fields", "Circuits", "Constant current sources"),
    "construction images created ideal thin lenses": ("Oscillations and waves", "Geometrical optics and photometry", "Construction of images created by ideal thin lenses"),
    "continuity energy flux": ("Oscillations and waves", "Waves", "Continuity of the energy flux"),
    "continuity heat flux": ("Thermodynamics and statistical physics", "Heat transfer and phase transitions", "Continuity of heat flux"),
    "continuity law": ("Mechanics", "Hydrodynamics", "Continuity law"),
    "coriolis acceleration zero": ("Mechanics", "Kinematics", "Recognition of the cases when the Coriolis acceleration is zero"),
    "coulomb force": ("Electromagnetic fields", "Basic concepts", "Coulomb force"),
    "current voltage resonance": ("Electromagnetic fields", "Circuits", "Current and voltage resonance"),
    "cyclotron frequency": ("Electromagnetic fields", "Interaction of matter with electric and magnetic fields", "Cyclotron frequency"),
    "dalton s law": ("Thermodynamics and statistical physics", "Heat transfer and phase transitions", "Dalton's law"),
    "dependence electric permittivity frequency": ("Oscillations and waves", "Interaction of electromagnetic waves with matter", "Dependence of electric permittivity on frequency (qualitatively)"),
    "dependence electric permittivity frequency qualitatively": ("Oscillations and waves", "Interaction of electromagnetic waves with matter", "Dependence of electric permittivity on frequency (qualitatively)"),
    "dielectric magnetic permeability": ("Electromagnetic fields", "Interaction of matter with electric and magnetic fields", "Dielectric and magnetic permeability"),
    "differential form ohm s law": ("Electromagnetic fields", "Interaction of matter with electric and magnetic fields", "Differential form of Ohm's law"),
    "diffraction grating": ("Oscillations and waves", "Interference and diffraction", "Diffraction grating"),
    "diffraction grating resolving power": ("Oscillations and waves", "Optical devices", "Diffraction grating and its resolving power"),
    "diffraction one two slits": ("Oscillations and waves", "Interference and diffraction", "Diffraction from one and two slits"),
    "dipole moment current loop": ("Electromagnetic fields", "Interaction of matter with electric and magnetic fields", "Dipole moment of a current loop"),
    "dispersion dissipation electromagnetic waves transparent opaque materials": ("Oscillations and waves", "Interaction of electromagnetic waves with matter", "Dispersion and dissipation of electromagnetic waves in transparent and opaque materials"),
    "dissipation friction": ("Mechanics", "Dynamics", "Dissipation due to friction"),
    "drift crossed e b fields": ("Electromagnetic fields", "Interaction of matter with electric and magnetic fields", "Drift in crossed E and B fields"),
    "eddy currents": ("Electromagnetic fields", "Interaction of matter with electric and magnetic fields", "Eddy currents"),
    "efficiency non ideal heat engines": ("Thermodynamics and statistical physics", "Classical thermodynamics", "Efficiency of non-ideal heat engines"),
    "electric field electrostatic potential surface conductors infinity": ("Electromagnetic fields", "Integral forms of Maxwell's equations", "Boundary conditions for the electric field (or electrostatic potential) at the surface of conductors and at infinity"),
    "electric field surface conductors infinity": ("Electromagnetic fields", "Integral forms of Maxwell's equations", "Boundary conditions for the electric field (or electrostatic potential) at the surface of conductors and at infinity"),
    "electron neutrinos": ("Quantum Physics", "Structure of matter", "Electron neutrinos"),
    "electrostatic field potential field": ("Electromagnetic fields", "Basic concepts", "Electrostatic field as a potential field"),
    "emission absorption spectra hydrogen like atoms": ("Quantum Physics", "Structure of matter", "Emission and absorption spectra for hydrogen-like atoms"),
    "energy": ("Mechanics", "Dynamics", "Energy"),
    "energy capacitors inductors": ("Electromagnetic fields", "Circuits", "Energy of capacitors and inductors"),
    "energy carried waves": ("Oscillations and waves", "Waves", "Energy carried by waves: proportionality to the square of the amplitude"),
    "energy carried waves proportionality square amplitude": ("Oscillations and waves", "Waves", "Energy carried by waves: proportionality to the square of the amplitude"),
    "energy density electric magnetic fields": ("Electromagnetic fields", "Interaction of matter with electric and magnetic fields", "Energy density of electric and magnetic fields"),
    "energy levels hydrogen like atoms": ("Quantum Physics", "Probability waves", "Energy levels of hydrogen-like atoms (circular orbits only)"),
    "energy levels hydrogen like atoms circular orbits": ("Quantum Physics", "Probability waves", "Energy levels of hydrogen-like atoms (circular orbits only)"),
    "energy levels nuclei": ("Quantum Physics", "Structure of matter", "Energy levels of nuclei (qualitatively)"),
    "energy levels nuclei qualitatively": ("Quantum Physics", "Structure of matter", "Energy levels of nuclei (qualitatively)"),
    "energy levels parabolic potentials": ("Quantum Physics", "Probability waves", "Energy levels of parabolic potentials"),
    "energy magnetic dipole magnetic field": ("Electromagnetic fields", "Interaction of matter with electric and magnetic fields", "Energy of a magnetic dipole in a magnetic field"),
    "energy momentum photons": ("Relativity", "Relativity", "Energy and momentum of photons"),
    "energy point mass elliptical orbit": ("Mechanics", "Celestial mechanics", "Energy of a point mass on an elliptical orbit"),
    "entropy": ("Thermodynamics and statistical physics", "Classical thermodynamics", "Entropy"),
    "equilibrium conditions": ("Mechanics", "Statics", "Equilibrium conditions: force balance (vectorially or in terms of projections)"),
    "equilibrium conditions force balance": ("Mechanics", "Statics", "Equilibrium conditions: force balance (vectorially or in terms of projections)"),
    "equilibrium conditions force balance vectorially terms projections": ("Mechanics", "Statics", "Equilibrium conditions: force balance (vectorially or in terms of projections)"),
    "equipartition theorem": ("Thermodynamics and statistical physics", "Classical thermodynamics", "Equipartition theorem"),
    "exponential decay": ("Quantum Physics", "Structure of matter", "Exponential decay"),
    "exponential decay damped oscillations": ("Oscillations and waves", "Single oscillator", "Exponential decay of damped oscillations"),
    "exponential decay waves propagating dissipative media": ("Oscillations and waves", "Waves", "Exponential decay for waves propagating in dissipative media"),
    "faraday s law": ("Electromagnetic fields", "Integral forms of Maxwell's equations", "Faraday's law"),
    "ferromagnetic materials": ("Electromagnetic fields", "Interaction of matter with electric and magnetic fields", "Ferromagnetic materials"),
    "finding center mass system summation integration": ("Mechanics", "Statics", "Finding the centre of mass of a system via summation or via integration"),
    "finding centre mass system summation integration": ("Mechanics", "Statics", "Finding the centre of mass of a system via summation or via integration"),
    "finding moment inertia integration": ("Mechanics", "Dynamics", "Finding a moment of inertia via integration"),
    "first second laws thermodynamics": ("Thermodynamics and statistical physics", "Classical thermodynamics", "First and second laws of thermodynamics"),
    "fission": ("Quantum Physics", "Structure of matter", "Fission"),
    "forward reverse carnot cycle ideal gas efficiency": ("Thermodynamics and statistical physics", "Classical thermodynamics", "Forward and reverse Carnot cycle on ideal gas and its efficiency"),
    "free oscillations lc circuits": ("Oscillations and waves", "Single oscillator", "Free oscillations of LC circuits"),
    "frequency": ("Oscillations and waves", "Single oscillator", "Frequency"),
    "fusion": ("Quantum Physics", "Structure of matter", "Fusion"),
    "gas constant": ("Thermodynamics and statistical physics", "Classical thermodynamics", "Gas constant"),
    "gauss law": ("Electromagnetic fields", "Integral forms of Maxwell's equations", "Gauss' law (for E- and B-fields)"),
    "gauss law e b fields": ("Electromagnetic fields", "Integral forms of Maxwell's equations", "Gauss' law (for E- and B-fields)"),
    "generation sine waves feedback lc resonator": ("Oscillations and waves", "Single oscillator", "Generation of sine waves by feedback in a LC-resonator"),
    "geometrical optics": ("Oscillations and waves", "Geometrical optics and photometry", "Approximation of geometrical optics: rays and optical images"),
    "geometrical optics rays optical images": ("Oscillations and waves", "Geometrical optics and photometry", "Approximation of geometrical optics: rays and optical images"),
    "gravitational potential": ("Mechanics", "Celestial mechanics", "Gravitational potential"),
    "grounded conductors": ("Electromagnetic fields", "Integral forms of Maxwell's equations", "Concept of grounded conductors"),
    "half life": ("Quantum Physics", "Structure of matter", "Half life"),
    "harmonic oscillations": ("Oscillations and waves", "Single oscillator", "Harmonic oscillations: equation of motion"),
    "harmonic oscillations equation motion": ("Oscillations and waves", "Single oscillator", "Harmonic oscillations: equation of motion"),
    "heat": ("Thermodynamics and statistical physics", "Classical thermodynamics", "Heat"),
    "heat conductivity": ("Thermodynamics and statistical physics", "Heat transfer and phase transitions", "Concept of heat conductivity"),
    "hooke s law": ("Mechanics", "Statics", "Hooke's law"),
    "huygens principle": ("Oscillations and waves", "Interference and diffraction", "Huygens' principle"),
    "hysteresis dissipation": ("Electromagnetic fields", "Interaction of matter with electric and magnetic fields", "Hysteresis and dissipation"),
    "ideal gas law": ("Thermodynamics and statistical physics", "Classical thermodynamics", "Ideal gas law"),
    "ideal non ideal batteries": ("Electromagnetic fields", "Circuits", "Ideal and non-ideal batteries"),
    "illuminance": ("Oscillations and waves", "Geometrical optics and photometry", "Illuminance"),
    "images created ideal thin lenses": ("Oscillations and waves", "Geometrical optics and photometry", "Construction of images created by ideal thin lenses"),
    "impedance resistors inductors capacitors combination circuits": ("Electromagnetic fields", "Circuits", "Impedance of resistors, inductors, capacitors, and combination circuits"),
    "inertial force": ("Mechanics", "Dynamics", "Inertial force"),
    "inertial non inertial frames reference": ("Mechanics", "Dynamics", "Inertial and non-inertial frames of reference"),
    "interference thin films": ("Oscillations and waves", "Interference and diffraction", "Interference due to thin films"),
    "interferometers": ("Oscillations and waves", "Optical devices", "Interferometers"),
    "internal energy": ("Thermodynamics and statistical physics", "Classical thermodynamics", "Internal energy"),
    "internal energy ideal gases": ("Thermodynamics and statistical physics", "Classical thermodynamics", "Internal energy of ideal gases"),
    "invariance spacetime interval rest mass": ("Relativity", "Relativity", "Invariance of the spacetime interval and of the rest mass"),
    "isothermal isobaric isochoric adiabatic processes": ("Thermodynamics and statistical physics", "Classical thermodynamics", "Isothermal, isobaric, isochoric, and adiabatic processes"),
    "joule s law": ("Electromagnetic fields", "Circuits", "Joule's law"),
    "kelvin s temperature scale": ("Thermodynamics and statistical physics", "Classical thermodynamics", "Kelvin's temperature scale"),
    "kepler s laws": ("Mechanics", "Celestial mechanics", "Kepler's laws (no derivation needed for first and third law)"),
    "kepler s laws derivation first third law": ("Mechanics", "Celestial mechanics", "Kepler's laws (no derivation needed for first and third law)"),
    "kinetic energy translational rotational motions": ("Mechanics", "Dynamics", "Kinetic energy for translational and rotational motions"),
    "kinetic theory ideal gases": ("Thermodynamics and statistical physics", "Classical thermodynamics", "Kinetic theory of ideal gases: Avogadro number"),
    "kinetic theory ideal gases avogadro number": ("Thermodynamics and statistical physics", "Classical thermodynamics", "Kinetic theory of ideal gases: Avogadro number"),
    "kirchhoff s current law": ("Electromagnetic fields", "Basic concepts", "Kirchhoff's current law"),
    "kirchhoff s voltage law": ("Electromagnetic fields", "Basic concepts", "Kirchhoff's voltage law"),
    "latent heat": ("Thermodynamics and statistical physics", "Heat transfer and phase transitions", "Latent heat"),
    "law gravity": ("Mechanics", "Celestial mechanics", "Law of gravity"),
    "laws calculation fields when integrand almost piece wise constant": ("Electromagnetic fields", "Integral forms of Maxwell's equations", "Using these laws for the calculation of fields when the integrand is almost piece-wise constant"),
    "length contraction": ("Relativity", "Relativity", "Length contraction"),
    "lenz s law": ("Electromagnetic fields", "Interaction of matter with electric and magnetic fields", "Lenz's law"),
    "lifetime excited states": ("Quantum Physics", "Structure of matter", "Lifetime of excited states"),
    "linear polarisation": ("Oscillations and waves", "Interaction of electromagnetic waves with matter", "Linear polarisation"),
    "linear polarization": ("Oscillations and waves", "Interaction of electromagnetic waves with matter", "Linear polarisation"),
    "linear resistors ohm s law": ("Electromagnetic fields", "Circuits", "Linear resistors and Ohm's law"),
    "linear speed": ("Mechanics", "Kinematics", "Linear speed"),
    "lorentz force": ("Electromagnetic fields", "Basic concepts", "Lorentz force"),
    "lorentz transformations energy momentum": ("Relativity", "Relativity", "Lorentz transformations for the energy and momentum"),
    "lorentz transformations time spatial coordinate": ("Relativity", "Relativity", "Lorentz transformations for the time and spatial coordinate"),
    "luminous flux continuity": ("Oscillations and waves", "Geometrical optics and photometry", "Luminous flux and its continuity"),
    "luminous intensity": ("Oscillations and waves", "Geometrical optics and photometry", "Luminous intensity"),
    "mach cone": ("Oscillations and waves", "Waves", "Mach cone"),
    "magnetic b field": ("Electromagnetic fields", "Basic concepts", "Magnetic B-field"),
    "malus law": ("Oscillations and waves", "Interaction of electromagnetic waves with matter", "Malus' law"),
    "mass defect": ("Quantum Physics", "Structure of matter", "Mass defect"),
    "mass energy equivalence": ("Relativity", "Relativity", "Mass-energy equivalence"),
    "mechanical work power": ("Mechanics", "Dynamics", "Mechanical work and power"),
    "mechano electrical analogy": ("Oscillations and waves", "Single oscillator", "Mechano-electrical analogy"),
    "method image charges": ("Electromagnetic fields", "Integral forms of Maxwell's equations", "Method of image charges"),
    "moment inertia integration": ("Mechanics", "Dynamics", "Finding a moment of inertia via integration"),
    "moment inertia simple bodies": ("Mechanics", "Dynamics", "Moment of inertia for simple bodies (ring, disk, sphere, hollow sphere, rod)"),
    "moment inertia simple bodies ring disk sphere hollow sphere rod": ("Mechanics", "Dynamics", "Moment of inertia for simple bodies (ring, disk, sphere, hollow sphere, rod)"),
    "momentum": ("Mechanics", "Dynamics", "Momentum"),
    "motion point particle constant acceleration": ("Mechanics", "Kinematics", "Motion of a point particle with a constant acceleration"),
    "motion rigid body rotation around instantaneous center rotation": ("Mechanics", "Kinematics", "Motion of a rigid body as a rotation around an instantaneous centre of rotation"),
    "motion rigid body rotation around instantaneous centre rotation": ("Mechanics", "Kinematics", "Motion of a rigid body as a rotation around an instantaneous centre of rotation"),
    "mutual inductance": ("Electromagnetic fields", "Circuits", "Mutual inductance"),
    "neutron capture": ("Quantum Physics", "Structure of matter", "Neutron capture"),
    "neutrons": ("Quantum Physics", "Structure of matter", "Neutrons"),
    "newton s second law": ("Mechanics", "Dynamics", "Newton's second law (in vector form and via projections (components))"),
    "newton s second law vector form projections components": ("Mechanics", "Dynamics", "Newton's second law (in vector form and via projections (components))"),
    "nonlinear elements given v i characteristic": ("Electromagnetic fields", "Circuits", "Nonlinear elements of given V-I characteristic"),
    "normal force": ("Mechanics", "Statics", "Normal force"),
    "ohmmeters": ("Electromagnetic fields", "Circuits", "Ohmmeters"),
    "open closed isolated systems": ("Thermodynamics and statistical physics", "Classical thermodynamics", "Open, closed, isolated systems"),
    "parallel axis theorem": ("Mechanics", "Dynamics", "Parallel axis theorem"),
    "parallel velocities": ("Relativity", "Relativity", "Addition of parallel velocities"),
    "partial shadow full shadow": ("Oscillations and waves", "Geometrical optics and photometry", "A partial shadow and full shadow"),
    "particles": ("Quantum Physics", "Structure of matter", "Particles (knowledge of charge and spin): electrons"),
    "particles electrons": ("Quantum Physics", "Structure of matter", "Particles (knowledge of charge and spin): electrons"),
    "particles knowledge charge spin electrons": ("Quantum Physics", "Structure of matter", "Particles (knowledge of charge and spin): electrons"),
    "particles waves": ("Quantum Physics", "Probability waves", "Particles as waves: relationship between the frequency and energy"),
    "particles waves relationship frequency energy": ("Quantum Physics", "Probability waves", "Particles as waves: relationship between the frequency and energy"),
    "pauli exclusion principle fermi particles": ("Quantum Physics", "Structure of matter", "Pauli exclusion principle for Fermi particles"),
    "period": ("Oscillations and waves", "Single oscillator", "Period"),
    "phase group velocities": ("Oscillations and waves", "Waves", "Phase and group velocities"),
    "phase shift steady state oscillations": ("Oscillations and waves", "Single oscillator", "Phase shift of steady state oscillations"),
    "phase transitions": ("Thermodynamics and statistical physics", "Heat transfer and phase transitions", "Phase transitions (boiling, evaporation, melting, sublimation)"),
    "phase transitions boiling evaporation melting sublimation": ("Thermodynamics and statistical physics", "Heat transfer and phase transitions", "Phase transitions (boiling, evaporation, melting, sublimation)"),
    "phase transitions boiling evapouration melting sublimation": ("Thermodynamics and statistical physics", "Heat transfer and phase transitions", "Phase transitions (boiling, evaporation, melting, sublimation)"),
    "phasor diagrams": ("Electromagnetic fields", "Circuits", "Phasor diagrams"),
    "photoelectric effect": ("Quantum Physics", "Structure of matter", "Photoelectric effect"),
    "photons": ("Quantum Physics", "Structure of matter", "Photons"),
    "physical pendulum reduced length": ("Oscillations and waves", "Single oscillator", "Physical pendulum and its reduced length"),
    "planck s law": ("Thermodynamics and statistical physics", "Statistical physics", "Planck's law (explained qualitatively, does not need to be remembered)"),
    "planck s law explained qualitatively remembered": ("Thermodynamics and statistical physics", "Statistical physics", "Planck's law (explained qualitatively, does not need to be remembered)"),
    "polarisers": ("Oscillations and waves", "Interaction of electromagnetic waves with matter", "Polarisers"),
    "polarizers": ("Oscillations and waves", "Interaction of electromagnetic waves with matter", "Polarisers"),
    "positive feedback source instability": ("Oscillations and waves", "Single oscillator", "Positive feedback as a source of instability"),
    "potential energy rotating frame": ("Mechanics", "Dynamics", "Potential energy in a rotating frame"),
    "potential energy simple force fields": ("Mechanics", "Dynamics", "Potential energy for simple force fields (also as a line integral of the force field)"),
    "potential energy simple force fields line integral force field": ("Mechanics", "Dynamics", "Potential energy for simple force fields (also as a line integral of the force field)"),
    "pressure": ("Mechanics", "Hydrodynamics", "Pressure"),
    "principle relativity": ("Relativity", "Relativity", "Principle of relativity"),
    "propagation harmonic waves": ("Oscillations and waves", "Waves", "Propagation of harmonic waves: phase as a linear function of space and time"),
    "propagation harmonic waves phase linear function space time": ("Oscillations and waves", "Waves", "Propagation of harmonic waves: phase as a linear function of space and time"),
    "protons": ("Quantum Physics", "Structure of matter", "Protons"),
    "protons neutrons compound particles": ("Quantum Physics", "Structure of matter", "Protons and neutrons as compound particles"),
    "quantization angular momentum": ("Quantum Physics", "Probability waves", "Quantization of angular momentum"),
    "recognition cases when coriolis acceleration zero": ("Mechanics", "Kinematics", "Recognition of the cases when the Coriolis acceleration is zero"),
    "refractive index": ("Oscillations and waves", "Interaction of electromagnetic waves with matter", "Refractive index"),
    "relationship wave vector momentum": ("Quantum Physics", "Probability waves", "Relationship between the wave vector and momentum"),
    "relative humidity": ("Thermodynamics and statistical physics", "Heat transfer and phase transitions", "Relative humidity"),
    "relative permittivity permeability electric magnetic materials": ("Electromagnetic fields", "Interaction of matter with electric and magnetic fields", "Relative permittivity and permeability of electric and magnetic materials"),
    "relativistic doppler effect": ("Relativity", "Relativity", "Relativistic Doppler effect"),
    "relativistic equation motion": ("Relativity", "Relativity", "Relativistic equation of motion"),
    "relativity simultaneity": ("Relativity", "Relativity", "Relativity of simultaneity"),
    "resistivity conductivity": ("Electromagnetic fields", "Interaction of matter with electric and magnetic fields", "Resistivity and conductivity"),
    "resonance sinusoidally forced oscillators": ("Oscillations and waves", "Single oscillator", "Resonance of sinusoidally forced oscillators: amplitude of steady state oscillations"),
    "resonance sinusoidally forced oscillators amplitude steady state oscillations": ("Oscillations and waves", "Single oscillator", "Resonance of sinusoidally forced oscillators: amplitude of steady state oscillations"),
    "root mean square speed molecules": ("Thermodynamics and statistical physics", "Classical thermodynamics", "Root-mean-square speed of molecules"),
    "saturated vapor pressure": ("Thermodynamics and statistical physics", "Heat transfer and phase transitions", "Saturated vapour pressure"),
    "saturated vapour pressure": ("Thermodynamics and statistical physics", "Heat transfer and phase transitions", "Saturated vapour pressure"),
    "self induction inductance": ("Electromagnetic fields", "Circuits", "Self-induction and inductance"),
    "snell s law": ("Oscillations and waves", "Waves", "Snell's law"),
    "sound waves": ("Oscillations and waves", "Waves", "Sound waves: speed as a function of pressure (Young's or bulk modulus) and density"),
    "sound waves speed function pressure density": ("Oscillations and waves", "Waves", "Sound waves: speed as a function of pressure (Young's or bulk modulus) and density"),
    "sound waves speed function pressure young s bulk modulus density": ("Oscillations and waves", "Waves", "Sound waves: speed as a function of pressure (Young's or bulk modulus) and density"),
    "specific heat isobaric isochoric processes": ("Thermodynamics and statistical physics", "Classical thermodynamics", "Specific heat for isobaric and isochoric processes"),
    "spectra atoms": ("Quantum Physics", "Structure of matter", "Spectra for other atoms (qualitatively)"),
    "spectra atoms qualitatively": ("Quantum Physics", "Structure of matter", "Spectra for other atoms (qualitatively)"),
    "spectra molecules molecular oscillations": ("Quantum Physics", "Structure of matter", "Spectra for molecules due to molecular oscillations"),
    "spectral width": ("Quantum Physics", "Structure of matter", "Spectral width"),
    "stable unstable equilibria": ("Mechanics", "Statics", "Stable and unstable equilibria"),
    "standing waves": ("Oscillations and waves", "Interference and diffraction", "Standing waves"),
    "static kinetic friction force": ("Mechanics", "Statics", "Static and kinetic friction force"),
    "stefan boltzmann law": ("Thermodynamics and statistical physics", "Statistical physics", "Stefan-Boltzmann law"),
    "strain": ("Mechanics", "Statics", "Strain"),
    "stress": ("Mechanics", "Statics", "Stress"),
    "superposition principle electric magnetic fields": ("Electromagnetic fields", "Integral forms of Maxwell's equations", "Superposition principle for electric and magnetic fields"),
    "superposition waves": ("Oscillations and waves", "Interference and diffraction", "Superposition of waves: coherence"),
    "superposition waves coherence": ("Oscillations and waves", "Interference and diffraction", "Superposition of waves: coherence"),
    "surface tension associated energy": ("Mechanics", "Hydrodynamics", "Surface tension and the associated energy"),
    "telescopes microscopes": ("Oscillations and waves", "Optical devices", "Telescopes and microscopes: magnification and resolving power"),
    "telescopes microscopes magnification resolving power": ("Oscillations and waves", "Optical devices", "Telescopes and microscopes: magnification and resolving power"),
    "tension force": ("Mechanics", "Statics", "Tension force"),
    "their conservation laws": ("Mechanics", "Dynamics", "Their conservation laws"),
    "thermal equilibrium reversible processes": ("Thermodynamics and statistical physics", "Classical thermodynamics", "Concepts of thermal equilibrium and reversible processes"),
    "thin lens approximation": ("Oscillations and waves", "Geometrical optics and photometry", "Thin lens approximation"),
    "thin lens equation": ("Oscillations and waves", "Geometrical optics and photometry", "Thin lens equation"),
    "time constants rl rc circuits": ("Electromagnetic fields", "Circuits", "Time constants for RL and RC circuits"),
    "time dilation": ("Relativity", "Relativity", "Time dilation"),
    "torque balance": ("Mechanics", "Statics", "Torque balance (only for one- and two-dimensional geometry)"),
    "torque balance one two dimensional geometry": ("Mechanics", "Statics", "Torque balance (only for one- and two-dimensional geometry)"),
    "translational motion molecules pressure": ("Thermodynamics and statistical physics", "Classical thermodynamics", "Translational motion of molecules and pressure"),
    "translational rotational oscillatory degrees freedom": ("Thermodynamics and statistical physics", "Classical thermodynamics", "Translational, rotational and oscillatory degrees of freedom"),
    "transverse longitudinal waves": ("Oscillations and waves", "Waves", "Transverse and longitudinal waves"),
    "uncertainty principle conjugate pairs time energy": ("Quantum Physics", "Probability waves", "Uncertainty principle for the conjugate pairs of time and energy"),
    "uncertainty principle coordinate momentum": ("Quantum Physics", "Probability waves", "Uncertainty principle for the coordinate and momentum"),
    "uniqueness solution well posed problems": ("Electromagnetic fields", "Integral forms of Maxwell's equations", "Uniqueness of solution to well-posed problems"),
    "velocities accelerations material points rigid rotating bodies": ("Mechanics", "Kinematics", "Velocities and accelerations of the material points of rigid rotating bodies"),
    "velocities angular velocities": ("Mechanics", "Kinematics", "Addition of velocities and angular velocities"),
    "velocity acceleration point particle derivatives displacement vector": ("Mechanics", "Kinematics", "Velocity and acceleration of a point particle as the derivatives of its displacement vector"),
    "voltmeters": ("Electromagnetic fields", "Circuits", "Voltmeters"),
    "wave vector": ("Oscillations and waves", "Waves", "Wave vector"),
    "wavelength": ("Oscillations and waves", "Waves", "Wavelength"),
    "waves inhomogeneous media": ("Oscillations and waves", "Waves", "Waves in inhomogeneous media: Fermat's principle"),
    "waves inhomogeneous media fermat s principle": ("Oscillations and waves", "Waves", "Waves in inhomogeneous media: Fermat's principle"),
    "wien s displacement law": ("Thermodynamics and statistical physics", "Statistical physics", "Wien's displacement law"),
    "work": ("Thermodynamics and statistical physics", "Classical thermodynamics", "Work"),
    "work done electromotive force": ("Electromagnetic fields", "Circuits", "Work done by an electromotive force"),
    "young modulus": ("Mechanics", "Statics", "Young modulus"),
}

# Total entries: 283
